report: 
  fileName: 'report'
  title: 'MetaSense Report' 

order: 
  report.ipynb: 1
  versions.ipynb: 2

options:
  exclude_input: True
  exclude_output_prompt: True
  exclude_input_prompt: True

parameters:
  brac_file: 'bracken_combined.tsv'
  sv_file: 'software_versions.yml'
